### ISSUE TITLE
header_text_feature_image not displayed properly on mobile(android) browser

### ISSUE THREAD

**Issue by yshrsmz** [Sylhare/Type-on-Strap#34]
https://yshrsmz.github.io/

So here is my page.
when I browse this page on Android Chrome, header_text_feature_image is not displayed properly(it's way smaller than the display). it's displayed at the left side at first, and when I scroll it will be aligned to right.

Your demo page's header image ( https://sylhare.github.io/Type-on-Strap/ ) also looks strange. its width looks like wider than the display, but when you scroll, it becomes same width as display

**Comment by yshrsmz** [comment]
Oh, it's not android problem, if you make your browser's width small enough, you'll see what I mean

**Comment by Sylhare** [comment]
Hi, can you do a screenshot, I have trouble seeing what you mean.

**Comment by yshrsmz** [comment]
Sorry for my english.
Here's screenshot's

|Before scroll|After scroll|
|---|---|
|<img src="https://user-images.githubusercontent.com/654889/33859181-16677768-df16-11e7-861b-23127bdd6f52.png" width="80%">|<img src="https://user-images.githubusercontent.com/654889/33859237-49b8d382-df16-11e7-862b-e40f24f76b46.png" width="80%">|
|<img src="https://user-images.githubusercontent.com/654889/33859293-87235e0e-df16-11e7-942f-92c0207f0c09.png" width="80%">|<img src="https://user-images.githubusercontent.com/654889/33859296-893ced54-df16-11e7-9e7c-6c914d52e6ec.png" width="80%">|

You can see obvious difference on my site. But even with your site, header image is wider than the parent width, and when you scroll, it matches parent's width.

https://github.com/yshrsmz/yshrsmz.github.io/blob/master/assets/img/dactyl.jpg
here's my image if you need.

thanks.

**Comment by Sylhare** [comment]
Ok I'll make some tests, thanks.

**Comment by Sylhare** [comment]
So, I fixed the glitch with the scrolling. (It should not move anymore now).

Now for your image, the blue (behind) is because of the image ratio (it should be a bit more rectangular like the one I am using).
So you can either:

- Crop your image to a better ratio
- Try with another image
- Update `_index/scss` in the `.call-out` check the "responsive" and update with something like:
```css
    
    /* --- Responsive ---*/
    @media screen and (max-width: 730px) {
        background-size: auto 200%;
    }

or remove it entirely.

**Comment by yshrsmz** [comment]
thanks!
Isn't it better to specify as `background-size: 100% auto;`?
I think with this way you can actually fit header image's width to the parent.

**Comment by yshrsmz** [comment]
I updated image with more rectangular one, but still having problem.
It looks like header image's width is depending on header text.
If you replace your header text with more shorter one(such as `<p>This is test header</p>`), your image will not be displayed properly

I've attached an image. I just replaced header text with `<p>test</p>`.
![screenshot](https://user-images.githubusercontent.com/654889/33871241-01802f0e-df55-11e7-962e-eb4a13dab3f4.png)

**Comment by Sylhare** [comment]
Oh that's interesting, I'll investigate ;)

**Comment by yshrsmz** [comment]
Let me correct my previous comment. it looks like header image's width is depending on the height of `div#main`. (Yes, this is what `background-size: auto 150%` means)

Since `auto` retains image's ratio, image cannot match the parent width if `div#main` does not have enough height,

**Comment by Sylhare** [comment]
Hi, since I don't have a solution for a scaling slightly bigger header image, I'll let it on `cover` that should solve your problem.
Once I have a solution I will re-implement the feature

**Comment by Sylhare** [comment]
I'll make it available only for short text, since it's not made to m=put as much text as I did. so I'm changing the _config.yml
It should be now 100% width on the page for smaller screen.
I'll merge the branch when ready.
